spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
minio:
  access-key: minioadmin
  endpoint: http://localhost:9000
  bucket: user-files
  secret-key: minioadmin


server:
  port: 8081